### ISSUE TITLE
Looking for system parameters of the simulated events

### ISSUE THREAD

**Issue by Somayeh91** [mikecokina/elisa_mlayer#6]
Dear Mike,

Very interesting paper! Great job!

I tried to get the observed lc table from the link you provided on this repo, but I am not able to use the file. I was wondering if you could provide instruction on how to use that file.
I was actually looking for the system parameters of the events you simulated for this project and was wondering if those are publicly available.

Best,
Somayeh Khakpash

**Comment by mikecokina** [comment]
Hello,

Thank You, I am glad you are interested in our paper.
Can you provide your email for better communication, since I am not able to
send attachments with files you are asking for.

Thank You.
Regards
Mike

pi 6. 8. 2021 o 17:15 Somayeh Khakpash ***@***.***>
napísal(a):

**Comment by Somayeh91** [comment]
I appreciate your fast response.
Sure! Here is my email: Somayeh.khakpash@gmail.com

Best,
Somayeh
